myShell: myShell.cpp parse.cpp parse.h searchCommand.cpp searchCommand.h launch.cpp launch.h 
	g++ -o myShell -Wall -Werror -pedantic -ggdb3 -std=gnu++98 myShell.cpp parse.cpp searchCommand.cpp launch.cpp
clean:
	rm -f *~ *# myShell